### ISSUE TITLE
module 'pyglet.gl' has no attribute 'xlib'

### ISSUE THREAD

**Issue by CathyLou** [mmatl/pyrender#113]
pyglet version is 1.4.10 and there is an error: module 'pyglet.gl' has no attribute 'xlib'
anyone can help me?

**Comment by kylinmb** [comment]
I experienced the same issue with pyrender version 0.1.40, the pyglet version installed as a dependency is 1.5.5. I am running MacOS 10.15.4 (Catalina).

### Steps to reproduce issue
1. `pip install pyrender`
2. In my code I called 
```python 
r = pyrender.OffscreenRenderer(width, height)
color, depth = r.render(scene)
```

#### Exception:
```
Traceback (most recent call last):
  File "/Users/kylimckay-bishop/Workspace/image-embedding-data/renderSupershapes.py", line 297, in <module>
    main()
  File "/Users/kylimckay-bishop/Workspace/image-embedding-data/renderSupershapes.py", line 135, in main
    color, depth = r.render(scene)
  File "/Users/kylimckay-bishop/miniconda3/envs/dSpaceX/lib/python3.7/site-packages/pyrender/offscreen.py", line 109, in render
    self._platform.make_uncurrent()
  File "/Users/kylimckay-bishop/miniconda3/envs/dSpaceX/lib/python3.7/site-packages/pyrender/platforms/pyglet_platform.py", line 54, in make_uncurrent
    pyglet.gl.xlib.glx.glXMakeContextCurrent(self._window.context.x_display, 0, 0, None)
AttributeError: module 'pyglet.gl' has no attribute 'xlib'

Process finished with exit code 1
```

### Workaround
Installing the previous version of pyrender resolved the issue for me:
```
pip install pyrender==0.1.39
```

**Comment by CathyLou** [comment]
thx so much
add  these two lines ⬇️ and it works 

import os
os.environ["PYOPENGL_PLATFORM"] = "osmesa"

**Comment by michele-arrival** [comment]
This is not a resolution. You have switched to software rendering with "osmesa". The problem with pyglet and OpenGL rendering on Windows and MacOS remains. It would be great to leave this issue open for the maintainer to see and fix it in the other use cases.

**Comment by michele-arrival** [comment]
see #117
