### ISSUE TITLE
EGL BAD DISPLAY

### ISSUE THREAD

**Issue by luoyuxuan0528** [mmatl/pyrender#146]
I am trying to use pyrender on headless server but face EGL BAD DISPLAY. Here is my code:
```
import os
os.environ["PYOPENGL_PLATFORM"] = "egl"
import pyrender
pyrender.offscreen.OffscreenRenderer(640, 480)
```
The error message is 
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    r = pyrender.OffscreenRenderer(640, 480)
  File "/usr/local/lib/python3.7/dist-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/usr/local/lib/python3.7/dist-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/usr/local/lib/python3.7/dist-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/usr/local/lib/python3.7/dist-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/usr/local/lib/python3.7/dist-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 12296,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7f9be7ed3c80>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)
```
Operation System:  Debian GNU/Linux 10. Libs installed by apt-get all:
- libsm6
- libxext6
- libgl1-mesa-glx
- freeglut3-dev
- libegl1-nvidia
- libxrender1
- libgeos-dev

I've googled for a long time and find nothing, any help? @mmatl

**Comment by JasonBoy1** [comment]
@mmatl

**Comment by shawkontzu** [comment]
Facing the similar issue for running opengl on headless machine using EGL.

**Comment by ZhengdiYu** [comment]
Any updates? @mmatl

**Comment by WilliamLLee** [comment]
I face the same error under CentOS system, and still not fix it yet! Did you fix this error?
