### ISSUE TITLE
color image have similar values on all channels

### ISSUE THREAD

**Issue by flugenheimer** [mmatl/pyrender#18]
I tried to run it with the view'er and it looks correct, but running it offscreen just gives the rgb values [38,38,38] where the object should be. The background has the correct color, and the depth image also looks correct.

**Comment by mmatl** [comment]
Which offscreen renderer are you using (pyglet, EGL, osmesa)?

**Comment by flugenheimer** [comment]
I tried egl and osmesa. 

I just tried using the script and model from the quickstart "minimal example of offscreen rendering" and when i run it using either egl or osmesa i get the following error 
`OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenVertexArrays, check for bool(glGenVertexArrays) before calling
` 
maybe i did not install something correctly? 

Sorry for the rookie questions - 3D rendering is a new area for me.

**Comment by mmatl** [comment]
No stress! Make sure to follow the instructions for installing OSMesa if you're using that (see here: https://pyrender.readthedocs.io/en/latest/install/index.html#getting-pyrender-working-with-osmesa). For EGL, some NVIDIA drivers work with it, while some don't - it can be a bit finnicky.

**Comment by mmatl** [comment]
@flugenheimer Were you able to fix your issue?

**Comment by staceycy** [comment]
Hi @mmatl , 

I ran into the same problem. 
Attached is my code: 
[py_render.txt](https://github.com/mmatl/pyrender/files/3160835/py_render.txt)

It gives following error when I use a monitor: 

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hdd1/6dpose/rendering/render_onto_desk.py", line 30, in <module>
    img, depth = py_render.render_object(model_file, dataset)
  File "/hdd1/6dpose/rendering/py_render.py", line 47, in render_object
    v = Viewer(scene, central_node=obj_node, shadows=False)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 347, in __init__
    self._init_and_start_app()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 1003, in _init_and_start_app
    pyglet.app.run()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/app/__init__.py", line 142, in run
    event_loop.run()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/app/base.py", line 164, in run
    self._legacy_setup()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/app/base.py", line 253, in _legacy_setup
    window.dispatch_pending_events()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 877, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *self._event_queue.pop(0))
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/event.py", line 370, in dispatch_event
    if handler(*args):
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 606, in on_resize
    self.on_draw()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 566, in on_draw
    self._render()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 985, in _render
    self._renderer.render(self.scene, flags)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/renderer.py", line 121, in render
    self._update_context(scene, flags)
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/renderer.py", line 709, in _update_context
    p._add_to_context()
  File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/primitive.py", line 324, in _add_to_context
    self._vaid = glGenVertexArrays(1)
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenVertexArrays, check for bool(glGenVertexArrays) before calling

**Comment by flugenheimer** [comment]
@mmatl: I tried installing osmesa again first by using the .deb file, which did not solve the issue, and then by building it from source, which also did not help. 

so i am still kind of stuck - is there another way to test if it has been installed correctly?

**Comment by flugenheimer** [comment]
Also tried it on another pc with a GTX 1080, with driver:  390.116   

could not get EGL to work

**Comment by liwenssss** [comment]
> Hi @mmatl ,
> 
> I ran into the same problem.
> Attached is my code:
> [py_render.txt](https://github.com/mmatl/pyrender/files/3160835/py_render.txt)
> 
> * **It gives following error when I use a monitor:**
>   File "/home/user/anaconda3/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 407, in **call**
>   self.**name**, self.**name**,
>   OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenVertexArrays, check for bool(glGenVertexArrays) before calling
> * **It gives following errors when I use SSH:**
>   File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 347, in **init**
>   self._init_and_start_app()
>   File "/home/user/anaconda3/lib/python3.7/site-packages/pyrender/viewer.py", line 995, in _init_and_start_app
>   height=self._viewport_size[1])
>   File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/window/xlib/**init**.py", line 170, in **init**
>   super(XlibWindow, self).**init**(*args, **kwargs)
>   File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/window/**init**.py", line 592, in **init**
>   config = screen.get_best_config(config)
>   File "/home/user/anaconda3/lib/python3.7/site-packages/pyglet/canvas/base.py", line 197, in get_best_config
>   raise window.NoSuchConfigException()
>   pyglet.window.NoSuchConfigException
> 
> Could you please help to give some advice?
> Thanks.

hello, have you solved the second error, I got the same error and don't know solve it.

**Comment by HaFred** [comment]
```
os.environ['PYOPENGL_PLATFORM'] = 'egl'
```
For those who try to do offscreen like me with this line, might get this error above. Removing this line helps.
