### ISSUE TITLE
error occurs when runing on the server

### ISSUE THREAD

**Issue by MengHao666** [mmatl/pyrender#183]
Hi, thanks for such great work.
It works well in my own PC.However, the following error occurs when I try to run in server.
How could I solve it?

> Traceback (most recent call last):
  File "save_render_mask7.py", line 266, in <module>
    save_render_mask(parser.parse_args())
  File "save_render_mask7.py", line 138, in save_render_mask
    renderer = pyrender.OffscreenRenderer(viewport_width=img_width, viewport_height=img_height, point_size=1.0)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/mnt/lustre/menghao/.local/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fd8c40801e0>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)
srun: error: SH-IDC1-10-5-36-168: task 0: Exited with exit code 1

**Comment by guan2000910** [comment]
Did you solve it? I have the same problem you have.

**Comment by Dariushuangg** [comment]
same problem

**Comment by smileyenot983** [comment]
Hi, any update on this?

**Comment by MengHao666** [comment]
> Did you solve it? I have the same problem you have.

not at all
