### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by anjugopinath** [mmatl/pyrender#188]
Pyrender version : 0.1.45
Python version (python virtual environment) : 3.8.3

I get the below error on executing "python render.py" from path 'tool/MANO_render': (https://github.com/facebookresearch/InterHand2.6M)

Traceback (most recent call last):
File "render.py", line 141, in
renderer = pyrender.OffscreenRenderer(viewport_width=img_width, viewport_height=img_height, point_size=1.0)
File "/s/red/a/nobackup/vision/anju/interhand_venv/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in init
self._create()
File "/s/red/a/nobackup/vision/anju/interhand_venv/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
self._platform.init_context()
File "/s/red/a/nobackup/vision/anju/interhand_venv/lib/python3.8/site-packages/pyrender/platforms/pyglet_platform.py", line 62, in init_context
'internal error message was "{}"'.format(e)
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by eyllanesc** [comment]
I found a similar error through flake8 so in #216 I have solved it.
