### ISSUE TITLE
pyglet.gl.ContextException: Could not create GL context

### ISSUE THREAD

**Issue by azuryl** [mmatl/pyrender#219]
I installed as guide https://pyrender.readthedocs.io/en/latest/install/index.html#python-installation
but error occur
detasets.py video 1/1 (1/343) /home/azuryl/data2/video/4p-c1_20212281641.mp4: orig_height, orig_width: 288 360
Traceback (most recent call last):
  File "track.py", line 663, in <module>
    detect(args)
  File "track.py", line 375, in detect
    renderer = Renderer(resolution=(orig_width, orig_height), orig_img=True,wireframe=False)
  File "/home/jliu/data2/V5_dSort_Vibe/VIBE/lib/utils/renderer.py", line 57, in __init__
    self.renderer = pyrender.OffscreenRenderer(
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyglet/window/__init__.py", line 523, in __init__
    context = config.create_context(gl.current_context)
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 191, in create_context
    return XlibContextARB(self, share)
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 297, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/home/jliu/anaconda3/envs/Mono3DPerson/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 205, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context

**Comment by submagr** [comment]
If running remotely over SSH, please make sure that you can display windows.

If not, [this thread](https://github.com/mmatl/pyrender/issues/13) might be helpful.
