### ISSUE TITLE
pyrender.Viewer(scene) OpenGL 3+ Error on Mac

### ISSUE THREAD

**Issue by sohils** [mmatl/pyrender#34]
I am running the following basic example:

```
import trimesh
import pyrender
fuze_trimesh = trimesh.load(OBJ FILE)
mesh = pyrender.Mesh.from_trimesh(fuze_trimesh)
scene = pyrender.Scene()
scene.add(mesh)
pyrender.Viewer(scene, use_raymond_lighting=True)
```

and I encounter this error on a Mac:

```
No handlers could be found for logger "trimesh"
Traceback (most recent call last):
  File "scripts/pyrender-trail.py", line 41, in <module>
    pyrender.Viewer(scene, use_raymond_lighting=True)
  File "/anaconda2/lib/python2.7/site-packages/pyrender/viewer.py", line 347, in __init__
    self._init_and_start_app()
  File "/anaconda2/lib/python2.7/site-packages/pyrender/viewer.py", line 997, in _init_and_start_app
    raise ValueError('Unable to initialize an OpenGL 3+ context')
ValueError: Unable to initialize an OpenGL 3+ context
```

**Comment by sohils** [comment]
The answer is to install the correct fork of `pyglet`.
https://pyrender.readthedocs.io/en/latest/install/index.html#python-installation
