### ISSUE TITLE
OSMesa Google CoLab Notebook Example no longer works

### ISSUE THREAD

**Issue by gcullie** [mmatl/pyrender#75]
[OSMesa Google CoLab Notebook](https://colab.research.google.com/drive/1Z71mHIc-Sqval92nK290vAsHZRUkCjUx) Example no longer works. 

```
ImportErrorTraceback (most recent call last)
<ipython-input-5-82e8b9d13125> in <module>()
     28 
     29 # Render the scene
---> 30 r = pyrender.OffscreenRenderer(640, 480)
     31 color, depth = r.render(scene)
     32 

1 frames
/usr/local/lib/python2.7/dist-packages/pyrender/offscreen.pyc in _create(self)
    125                                              device=egl_device)
    126         elif os.environ['PYOPENGL_PLATFORM'] == 'osmesa':
--> 127             from pyrender.platforms.osmesa import OSMesaPlatform
    128             self._platform = OSMesaPlatform(self.viewport_width,
    129                                             self.viewport_height)
```

ImportError: No module named osmesa

**Comment by jnyjxn** [comment]
I'm having the same issue with OSMesa.

And when I try to use `os.environ['PYOPENGL_PLATFORM'] = 'egl'` instead I get:

> File "/home/<>/anaconda2/envs/angiosynth/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
>  self._create()
> File "/home/<>/anaconda2/envs/angiosynth/lib/python3.7/site-packages/pyrender/offscreen.py", line 120, in _create
> from pyrender.platforms import egl
> ImportError: cannot import name 'egl' from 'pyrender.platforms' 
> (/home/<>/anaconda2/envs/angiosynth/lib/python3.7/site-packages/pyrender/platforms.py)

**Comment by jnyjxn** [comment]
Having looked into the files, it seems that it may be the `pip` package is behind or broken.

There is an error in offscreen.py in the `_create` function where it tries to `from pyrender.platforms.pyglet import PygletPlatform` or `from pyrender.platforms.osmesa import OSMesaPlatform`.

However, though there is indeed a `pyrender/platforms` folder in the repo, the version installed via pip is missing this folder and hence fails.

**Comment by jnyjxn** [comment]
It's the setup.py file that's broken.

It would be fixed by this pull request: https://github.com/mmatl/pyrender/pull/74

**Comment by TruongKhang** [comment]
@jnyjxn, I followed your suggestion which makes a change in file setup.py. But I still get the same error. I don't understand why

**Comment by jnyjxn** [comment]
What's the full error message?

**Comment by TruongKhang** [comment]
I still can not import esl and osmega

```>>> from pyrender.platforms import esl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'esl'`

**Comment by jnyjxn** [comment]
Have you installed OSMesa?

https://pyrender.readthedocs.io/en/latest/install/index.html#installmesa

**Comment by TruongKhang** [comment]
Yes, of course I did. But maybe this error comes from the system can not find the file esl.py and osmega.py in foler pyrender/platforms

**Comment by gngdb** [comment]
Neither the EGL or OSMesa notebook exists anymore, [links in the documentation](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html#google-colab-examples) lead nowhere.
