### ISSUE TITLE
pyrender.OffscreenRenderer fail

### ISSUE THREAD

**Issue by liwenssss** [mmatl/pyrender#81]
Hello, I run a test code:
```
import os
os.environ['PYOPENGL_PLATFORM'] = 'osmesa'
import pyrender

pyrender.OffscreenRenderer(viewport_width=224, viewport_height=224,point_size=1.0)
```  
and got the error:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    point_size=1.0)
  File "/home/liwensh2/.conda/envs/SPIN/lib/python3.6/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/liwensh2/.conda/envs/SPIN/lib/python3.6/site-packages/pyrender/offscreen.py", line 135, in _create
    self._platform.make_current()
  File "/home/liwensh2/.conda/envs/SPIN/lib/python3.6/site-packages/pyrender/platforms/osmesa.py", line 44, in make_current
    self.viewport_width, self.viewport_height
AssertionError
````
can you give me some help?Thanks!

**Comment by liwenssss** [comment]
After I build omesa from source , got the same error. Need Help orz..

**Comment by nfrik** [comment]
I keep on getting the same error.

I was able to reproduce it in different Docker containers, by simply installing pyrender and libosmesa6-dev.

`Traceback (most recent call last):
  File "pyrender_example.py", line 30, in <module>
    r = pyrender.OffscreenRenderer(640, 480)
  File "/notebooks/voca/pyrender/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/notebooks/voca/pyrender/pyrender/offscreen.py", line 135, in _create
    self._platform.make_current()
  File "/notebooks/voca/pyrender/pyrender/platforms/osmesa.py", line 44, in make_current
    self.viewport_width, self.viewport_height
AssertionError`

Searching on forums suggests that Mesa can't create OpenGL context.

Any help would be appreciated.

**Comment by huybery** [comment]
same error, any help would be appreciated.

**Comment by lucivpav** [comment]
My problem was probably causes by the fact that I originally compiled OSMesa v18.0.0 from source, not following the [instructions](https://pyrender.readthedocs.io/en/latest/install/index.html#building-from-source). Installing the (recommended?) version OSMesa v18.3.3 fixed the problem for me. Don't forget to update the environment variables, so they do not contain a path to the former mesa directory. The configuration I used that worked for me:

```
./configure --prefix=PREFIX \
	--enable-opengl --disable-gles1 --disable-gles2      \
	--disable-va --disable-xvmc --disable-vdpau          \
	--enable-shared-glapi                                \
	--disable-texture-float                              \
	--with-gallium-drivers=swrast,swr                    \
	--disable-dri --with-dri-drivers=                    \
	--disable-egl --with-egl-platforms= --disable-gbm    \
	--disable-glx                                        \
	--disable-osmesa --enable-gallium-osmesa
```

**Comment by YunjieYu** [comment]
I am experiencing the same problem in version 0.1.45. Does anyone have solved this problem?
