### ISSUE TITLE
EGL headless rendering sometimes works, sometimes not

### ISSUE THREAD

**Issue by guy4261** [mmatl/pyrender#92]
I have two identical Ubuntu machines in the cloud, where I run the code from the [EGL offscreen rendering colab notebook](https://colab.research.google.com/drive/1rTLHk0qxh4dn8KNe-mCnN8HAWdd2_BEh) as a Python script. One renders the bottle well, while the other gives me this error:

```python
Traceback (most recent call last):
  File "colab", line 30, in <module>
    r = pyrender.OffscreenRenderer(640, 480)
  File "/miniconda/envs/foo/lib/python3.6/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/miniconda/envs/foo/lib/python3.6/site-packages/pyrender/offscreen.py", line 134, in _create
    self._platform.init_context()
  File "/miniconda/envs/foo/lib/python3.6/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/miniconda/envs/foo/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/miniconda/envs/foo/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 12290,
	baseOperation = eglInitialize,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7f7c9f107400>,
		c_long(0),
		c_long(0),
	),
	result = 0
)
```
This seems similar to be the same as: https://github.com/deepmind/dm_control/issues/70
but I have no idea how to apply something similar for pyrender. Any ideas?

p.s.

I did not employ [this supposed fix](https://github.com/mcfletch/pyopengl/issues/27#issuecomment-511124488) in any of the machines, yet one works while the other fails, so I don't think that's the problem.

**Comment by guy4261** [comment]
Does it make sense that if my nvidia device is `/dev/nvidia1` or `/dev/nvidia2` then it doesn't get picked up as the `egl.EGL_DEFAULT_DISPLAY`? Is there an environment variable I should set for this case? (Like I'm setting `PYOPENGL_PLATFORM=egl` before import `pyrender`?)

**Comment by Guptajakala** [comment]
@guy4261 Hi, I'm meeting the same issue. Have you resolve it?
On my machine I indeed have /dev/nvidia0 but still get that error. Are you sure your two machines have the only difference in that /dev/nvidia id?

**Comment by guy4261** [comment]
@Guptajakala sorry - 1. I didn't solve this, 2. I do believe that on my machine it's the `/dev/nvidiaN` issue, perhaps you are experiencing something else I can't help with :(

**Comment by keunhong** [comment]
I submitted a PR (https://github.com/mmatl/pyrender/pull/60) a couple months ago that does this.

Just set the environment variable `EGL_DEVICE_ID` e.g.

```
export EGL_DEVICE_ID=1
python run.py
```

**Comment by guy4261** [comment]
Great @keunhong !!! Thanks!!!
Does this mean I should for now build from `master` rather then install with `pip`?

**Comment by Guptajakala** [comment]
@guy4261 I dont think you need. Just run export EGL_DEVICE_ID=1 before you run your python file.
However, it still doesn't work in my case, maybe my server has some wierd things. Please let me know if it works for you.

**Comment by keunhong** [comment]
> Great @keunhong !!! Thanks!!!
> Does this mean I should for now build from `master` rather then install with `pip`?

Looks like the commit should be in 0.1.33 so shouldn't be necessary.

**Comment by oarriaga** [comment]
I also had the following issue:

`OpenGL.error.GLError: GLError(	err = 12290,`

It was related to incompatible versions of pyrender and PyOpenGL.

**Comment by grgkopanas** [comment]
@oarriaga What was the incompatibility issue and what was eventually the compatible versions that you used?

**Comment by vstadnytskyi-FDA** [comment]
> I submitted a PR (#60) a couple months ago that does this.
> 
> Just set the environment variable `EGL_DEVICE_ID` e.g.
> 
> ```
> export EGL_DEVICE_ID=1
> python run.py
> ```

How do I do this on Windows 11?
