### ISSUE TITLE
time.clock error (and others) in pyglet with Python 3.8

### ISSUE THREAD

**Issue by patrikhuber** [mmatl/pyrender#95]
Environment: Python 3.8.1, 64-bit, Windows 10.

The pyrender minimal 3D viewer example fails with the following errors:

```
Traceback (most recent call last):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'Window'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'get_default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrender\__init__.py", line 12, in <module>
    from .viewer import Viewer
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyrender\viewer.py", line 36, in <module>
    class Viewer(pyglet.window.Window):
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\window\__init__.py", line 1859, in <module>
    from pyglet.window.win32 import Win32Window as Window
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\window\win32\__init__.py", line 59, in <module>
    from pyglet.canvas.win32 import Win32Canvas
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\canvas\__init__.py", line 63, in <module>
    from pyglet.app import WeakSet
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\app\__init__.py", line 163, in <module>
    event_loop = EventLoop()
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\app\base.py", line 152, in __init__
    self.clock = clock.get_default()
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "C:\Users\Patrik\AppData\Local\Programs\Python\Python38\lib\site-packages\pyglet\clock.py", line 137, in <module>
    _default_time_function = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

I believe these are related to Python 3.8, see e.g. https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8.

**Comment by patrikhuber** [comment]
These problems are fixed in the latest pyglet versions (i.e. 1.4.8). However when I update pyglet I get `ERROR: pyrender 0.1.33 has requirement pyglet==1.4.0b1, but you'll have pyglet 1.4.8 which is incompatible.`.

So, pyrender should update its dependencies, I guess?

**Comment by mmatl** [comment]
@patrikhuber This is fixed in the newest release. Thanks so much for the issue!

**Comment by patrikhuber** [comment]
@mmatl Thanks a lot for the update! I will make sure to give pyrender another go :-)

**Comment by lan786** [comment]
@patrikhuber  Hi, how we can install Pyrender in windows? I mean how to install dependence libraries like OpenGL in windows?

**Comment by patrikhuber** [comment]
@lan786 I just did `pip install pyrender` back then, or whatever the Readme suggests, I followed it. I wouldn't expect to have to install any libraries by hand?

**Comment by lan786** [comment]
@patrikhuber Thanks for your quick response. So Pyrender is working in your PC with Windows? 
How you get DLLs files for OpenGL? 
When I install Pyrender then it also install OpenGL 3.1.0 from pip and OpenGL not working even this [sample code for OpenGL](http://cim.mcgill.ca/~fmannan/comp557/pyopengl_sample.py) also not  working because from pip there no any DLLs folder in OpenGL. So I searched out the problem and when I installed OpenGL 3.1.5 from whl [from this link](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl) then [sample code for OpenGL](http://cim.mcgill.ca/~fmannan/comp557/pyopengl_sample.py) is working fine and also DLLs folder is there in OpenGL. Below is the output

![Capture](https://user-images.githubusercontent.com/40846865/75306555-5bf60a80-5884-11ea-9c0d-665d9dc60ab6.PNG)

When I test Pyrender [EGL Google CoLab Notebook](https://colab.research.google.com/drive/1rTLHk0qxh4dn8KNe-mCnN8HAWdd2_BEh) then I'm getting below error. Its due to EGL

![po](https://user-images.githubusercontent.com/40846865/75307526-e3447d80-5886-11ea-89d8-9d6330ce71f0.jpg)

My system environment is Windows 10, Anaconda Python 3.7

Can you sort out my problem regarding above errors? 
Waiting for your kind suggestions.

**Comment by patrikhuber** [comment]
@lan786 I think you should best open a new issue, as your question/issue is completely unrelated to this one which is closed.

By the way I am not a pyrender dev, I haven't even gotten to really using it, so I am not the right person to ask.

**Comment by patrikhuber** [comment]
I can confirm PyRender's minimal 3D viewer example now works fine on Windows with Python 3.8. Had to do no extra steps. Nice!

**Comment by duggalrd** [comment]
Hey @patrikhuber, thank you so much for creating this amazing library! Just a quick question as I am dealing with a similar error and I think this thread is the best place to ask.. 

Since you are able to get PyRender's  minimal 3D viewer working, I was wondering, did you load the mesh`from_trimesh()`? If so, can you tell me the params you have used when creating the TriMesh? I have tried the following but it is giving me an error, when I try to view the scene: 
`tri_mesh = trimesh.Trimesh(vertices=mesh.vertices, faces=mesh.tvi, vertex_colors=mesh.colors)`

Here is the full code if you are interested: 

       `(mesh, pose, shape_coeffs, blendshape_coeffs) = eos.fitting.fit_shape_and_pose(morphablemodel_with_expressions,
            landmarks, landmark_mapper, image_width, image_height, edge_topology, contour_landmarks, model_contour)   
        
        tri_mesh = trimesh.Trimesh(vertices=mesh.vertices, faces=mesh.tvi, vertex_colors=mesh.colors)

        rendered_mesh = pyrender.Mesh.from_trimesh(tri_mesh)

        scene = pyrender.Scene()

        scene.add(rendered_mesh)

        pyrender.Viewer(scene)`

**Comment by patrikhuber** [comment]
Hi @duggalrd, I assume you mean my [eos library](https://github.com/patrikhuber/eos) - thanks a lot.

The `mesh` member variables contain just a list of the vertex positions, triangle indices and vertex colours, all as NumPy arrays. So you can check the documentation of Trimesh (or perhaps PyRender) of how to create/render a mesh when you've got these things as NumPy arrays.

If you've got further problems, perhaps the place to post them would be StackOverflow, and posting the actual error that you get would for sure help. This is certainly the wrong place here.
